site_name: 'Example Documentation'
repo_url: https://github.com/cassiecsouza/opa-sandbox

nav:
  - What is Backstage?: 'https://backstage.io'
  - Architecture overview: 'overview/architecture-overview.md'
plugins:
  - techdocs-core

