site_name: 'Example Documentation'
repo_url: https://github.com/cassiecsouza/opa-sandbox
edit_uri: docs

nav:
  - Overview:
    - Home: index.md
    - What is Backstage?: 'https://backstage.io'
    - Architecture overview: 'overview/architecture-overview.md'
    - Project Roadmap: 'overview/roadmap.md'
    - Vision: 'overview/vision.md'
    - The Spotify Story: 'overview/background.md'
    - Strategies for adopting: 'overview/adopting.md'
    - Release & Versioning Policy: 'overview/versioning-policy.md'
    - Backstage Threat Model: 'overview/threat-model.md'
    - Support and community: 'overview/support.md'
    - Logo assets: 'overview/logos.md'
plugins:
  - techdocs-core

