pipeline:
    name: opa_pipeline
    identifier: opa_pipeline
    projectIdentifier: <UPDATE_ME>
    orgIdentifier: default
    tags: {}
    stages:
        - stage:
              name: SKO OPA Lab Steps
              identifier: SKO_OPA_Lab_Steps
              description: ""
              type: Deployment
              spec:
                  serviceConfig:
                      serviceRef: opalab
                      serviceDefinition:
                          type: Kubernetes
                          spec:
                              variables: []
                  infrastructure:
                      environment:
                          name: SKO
                          identifier: SKO
                          type: Production
                      infrastructureDefinition:
                          type: KubernetesDirect
                          spec:
                              connectorRef: account.mansong_gke
                              namespace: default
                              releaseName: release-<+INFRA_KEY>
                      allowSimultaneousDeployments: false
                  execution:
                      steps:
                          - step:
                                type: HarnessApproval
                                name: Approval Step
                                identifier: Approval_Step
                                spec:
                                    approvalMessage: Please review the following information and approve the pipeline progression
                                    includePipelineExecutionHistory: true
                                    approvers:
                                        userGroups:
                                            - account.Global_SE
                                        minimumCount: 1
                                        disallowPipelineExecutor: false
                                    approverInputs: []
                                timeout: 1d
                          - step:
                                type: ShellScript
                                name: Forbidden Shell Commands
                                identifier: Forbidden_Shell_Commands
                                spec:
                                    shell: Bash
                                    onDelegate: true
                                    source:
                                        type: Inline
                                        spec:
                                            script: |
                                                echo "Hello SKO people!"
                                    environmentVariables: []
                                    outputVariables: []
                                    executionTarget: {}
                                timeout: 10m
                      rollbackSteps: []
                  serviceDependencies: []
              tags: {}
              failureStrategies:
                  - onFailure:
                        errors:
                            - AllErrors
                        action:
                            type: StageRollback
