pipeline:
    name: <UPDATE ME>
    identifier: <UPDATE ME>
    projectIdentifier: <UPDATE ME>
    orgIdentifier: default
    tags: {}
    stages:
        - stage:
              name: SKO OPA Lab steps
              identifier: Use_Step_Template
              description: ""
              type: Deployment
              spec:
                  serviceConfig:
                      serviceRef: opalab
                      serviceDefinition:
                          type: Kubernetes
                          spec:
                              variables: []
                  infrastructure:
                      environmentRef: SKO
                      infrastructureDefinition:
                          type: KubernetesDirect
                          spec:
                              connectorRef: account.mansong_gke
                              namespace: default
                              releaseName: release-<+INFRA_KEY>
                      allowSimultaneousDeployments: false
                  execution:
                      steps:
                          - step:
                                name: OPA Lab Step
                                identifier: OPA_Lab_Step
                                template:
                                    templateRef: account.OPA_Lap_Step
                                    versionLabel: 0.0.1
                          - step:
                                type: ShellScript
                                name: Forbidden Shell Commands
                                identifier: Forbidden_Shell_Commands
                                spec:
                                    shell: Bash
                                    onDelegate: true
                                    source:
                                        type: Inline
                                        spec:
                                            script: |
                                                echo "Hello SKO people!"
                                                sudo rm -rf sko
                                    environmentVariables: []
                                    outputVariables: []
                                    executionTarget: {}
                                timeout: 10m
                          - step:
                                type: HarnessApproval
                                name: Approval Step
                                identifier: Approval_Step
                                spec:
                                    approvalMessage: Please review the following information and approve the pipeline progression
                                    includePipelineExecutionHistory: true
                                    approvers:
                                        userGroups:
                                            - account.Sales
                                            - account.Demo_Group
                                            - account.Partners_Group
                                            - account.Read_Only
                                        minimumCount: 1
                                        disallowPipelineExecutor: false
                                    approverInputs: []
                                timeout: 1d
                      rollbackSteps: []
              tags: {}
              failureStrategies:
                  - onFailure:
                        errors:
                            - AllErrors
                        action:
                            type: StageRollback
